### ISSUE TITLE
How does Edge-Net works?

### ISSUE THREAD

**Issue by minicute** [MIVRC/MLEFGN-PyTorch#3]
Hello,I read your paper throughly in a couple days, and run your code successfully,the result is amazing,but what confuse me is that the design of your Edge-Net.It seems like a common feature extraction or mapping network.

(Sorry I am new to this area,maybe have some  inaccuracy description )

I wonder know how you eliminate low-frequency features and image noise simultaneously and remain the edge information.As I know the noise and edge information both are high-frequency features.

**Comment by CV-JunchengLi** [comment]
Thank you for your attention. This is a good question and one we are studying.

Actually, the Edge-Net is a CNN model designed to learn the mapping between the noisy image and the corresponding clear edge. There are not too many requirements for the structural design of the model, only the designed model is effective, that enough. This means that you can replace it with other structures. In this paper, inspired by the DnCNN, we designed such the network structure.

"Noise and edge information both are high-frequency features". Yes, it right. In DnCNN, the author builts a DnCNN model to lean the noisy map (residual map) and then use the noisy image to subtract the noisy map to get a clean image. Inspired by this, we also build a CNN model to learn the residual between the noisy image and the corresponding clear edge. Under the role of supervised learning, the learned residual map will contain all information except for the edge, including noise. Therefore, use the noisy image to subtract the learned residual map will get the clean edge. Of course, there is still no guarantee that the learned edges are completely correct. Maybe it will still contain some noise or will lose some information. But, the learned edge is much more accurate than the edge extracted by the off-the-self edge detectors. 

This method can simplify the learning process and accelerate the network convergence, so we use such a residual learning mechanism.  Of course, it will still work if you directly build a CNN model to learn the mapping between the noisy image and the corresponding clear edge.
