### ISSUE TITLE
How to run test code?

### ISSUE THREAD

**Issue by KSJhon** [MIVRC/MLEFGN-PyTorch#5]
I made an environment with pytorch 0.4.1 and python 3.6 on ubuntu 18.
But i cannot run test code, I followed your instruction but i met the following message:
Exception has occurred: AttributeError
module 'model' has no attribute 'Model'
  File "/.../MLEFGN-PyTorch-master/TestCode/code/main.py", line 15, in <module>
    model = model.Model(args, checkpoint)

What is the reason?
Please help me.

**Comment by majunyao** [comment]
I have the same problem, would you solve it?

**Comment by majunyao** [comment]
I made an environment with pytorch 0.4.0 and python 3.6 on win 10

**Comment by CV-JunchengLi** [comment]
I lost a file before and I have updated the code.
