### ISSUE TITLE
Can't reproduce test result

### ISSUE THREAD

**Issue by KenYu910645** [MIVRC/MLEFGN-PyTorch#6]
Hi, I'm trying to reproduce the testing result, but currently all I get is bizarre images as I show below. I'm using pre-trained model and testing data that already inside the repo.
My Environment:
Ubuntu 18.04
python 3.6.13
pytorch 0.4.0
torchvision 0.2.0
cuda 9.0

Command I run: 
```
python main.py --data_test MyImage --scale 1 --model MLEFGN --pre_train ../model/15_gray.pt --test_only --save_results --chop --save "MLEFGN_Gray_15" --testpath ../LR/LRBI --testset Set12 --cpu
```

Input image:
![0805x1_ori](https://user-images.githubusercontent.com/33457769/144623024-89618ad4-3afc-4451-844d-1e74d5ae3c07.png)
Output images(denoised):
![0805x1](https://user-images.githubusercontent.com/33457769/144623017-b2e3f486-1160-44e6-86b9-28af26812d93.png)

**Comment by CV-JunchengLi** [comment]
This may be caused by the renaming of the model and module names during the post-organization of the code I uploaded.  I will look for the model file corresponding to the pre-trained model and upload it again

**Comment by CV-JunchengLi** [comment]
I have uploaded the original model file. The original model name is mlegn. So, maybe you can change the name of the pre-trained as mlegn for easy reproduce the results.
